/* لوحة السحابة: كل نشاط + من أضافه + تعديل المفتش */
(function(){'use strict';const P=window.PortalCloud;if(!P)return;
const esc=t=>String(t??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const RL={inspector:'مفتش',supervisor:'مشرف',teacher:'أستاذ'};
function dlg(title,val,ok){const d=document.createElement('div');d.style.cssText='position:fixed;inset:0;background:rgba(0,0,0,.6);z-index:99999;display:flex;align-items:center;justify-content:center';
d.innerHTML=`<div style="background:#fff;color:#222;padding:16px;border-radius:12px;width:min(94vw,640px)"><b>${esc(title)}</b><textarea style="width:100%;height:280px;margin:8px 0;direction:ltr;font-family:monospace">${esc(val)}</textarea><button data-s>حفظ</button> <button data-x>إلغاء</button></div>`;
d.querySelector('[data-x]').onclick=()=>d.remove();d.querySelector('[data-s]').onclick=async()=>{if(await ok(d.querySelector('textarea').value))d.remove()};document.body.appendChild(d)}
addEventListener('DOMContentLoaded',async()=>{const c=await P.ready;const{data:s}=await c.auth.getSession();if(!s.session)return;
const{data:me}=await c.from('wajih_profiles').select('*').eq('id',s.session.user.id).single();if(!me||!['inspector','supervisor'].includes(me.role))return;
const I=me.role==='inspector',box=document.createElement('section');box.style.cssText='max-width:1200px;margin:24px auto;padding:16px;direction:rtl;font-family:Tajawal,sans-serif;overflow-x:auto';document.body.appendChild(box);
async function draw(){const[{data:D},{data:U}]=await Promise.all([c.from('portal_data').select('*').order('updated_at',{ascending:false}),c.from('wajih_profiles').select('*').order('created_at')]);
box.innerHTML=`<h2>☁️ النشاطات المتزامنة مع Supabase</h2><p style="font-size:13px">${I?'يمكنك تعديل أي نشاط أو حذفه.':'عرض فقط: التعديل للمفتش.'}</p>
<table style="width:100%;border-collapse:collapse;font-size:13px"><tr><th>النشاط</th><th>أضافه</th><th>آخر تحديث</th><th>الحجم</th><th></th></tr>${(D||[]).map(r=>`<tr style="border-top:1px solid #ddd"><td>${esc(r.key)}${r.shared?' 🌐':''}</td><td>${esc(r.updated_by_name)} <small>(${RL[r.updated_by_role]||''})</small>${r.edited_by_name?`<br><small>عدّله: ${esc(r.edited_by_name)}</small>`:''}</td><td>${new Date(r.updated_at).toLocaleString('ar-DZ')}</td><td>${(r.value||'').length}</td><td><button data-v="${esc(r.owner)}|${esc(r.key)}">${I?'عرض/تعديل':'عرض'}</button>${I?` <button data-d="${esc(r.owner)}|${esc(r.key)}">حذف</button>`:''}</td></tr>`).join('')||'<tr><td>لا نشاط بعد</td></tr>'}</table>
<h2>👥 الحسابات</h2><table style="width:100%;font-size:13px;border-collapse:collapse">${(U||[]).map(u=>`<tr style="border-top:1px solid #ddd"><td>${esc(u.username)}</td><td>${esc(u.full_name)}</td><td>${RL[u.role]}</td><td>${u.active?'مفعّل':'معطّل'}${u.must_change?' · بانتظار التأمين':''}</td><td>${I&&u.id!==me.id?`<button data-t="${u.id}|${u.active}">${u.active?'تعطيل':'تفعيل'}</button>`:''}</td></tr>`).join('')}</table>
${I?`<div style="margin-top:10px"><input id="cu" placeholder="اسم المستخدم"> <input id="cf" placeholder="الاسم الكامل"> <select id="cr"><option value="teacher">أستاذ</option><option value="supervisor">مشرف</option><option value="inspector">مفتش</option></select> <input id="cp" type="password" placeholder="كلمة مرور مؤقتة (10+)"> <button id="ca">إضافة حساب</button></div>`:''}`;
box.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{const[o,k]=b.dataset.v.split('|'),r=D.find(x=>x.owner===o&&x.key===k);
dlg(k,r.value,async v=>{if(!I)return true;let j=false;try{JSON.parse(r.value);j=true}catch(e){}if(j)try{JSON.parse(v)}catch(e){alert('صيغة JSON غير صالحة');return false}
const{error}=await c.from('portal_data').update({value:v,updated_at:new Date().toISOString(),edited_by_name:me.full_name||me.username,edited_at:new Date().toISOString()}).eq('owner',o).eq('key',k);if(error){alert(error.message);return false}draw();return true})});
box.querySelectorAll('[data-d]').forEach(b=>b.onclick=async()=>{if(!confirm('حذف هذا النشاط نهائياً؟'))return;const[o,k]=b.dataset.d.split('|');await c.from('portal_data').delete().eq('owner',o).eq('key',k);draw()});
box.querySelectorAll('[data-t]').forEach(b=>b.onclick=async()=>{const[id,a]=b.dataset.t.split('|');await c.from('wajih_profiles').update({active:a!=='true'}).eq('id',id);draw()});
const ca=box.querySelector('#ca');if(ca)ca.onclick=async()=>{const u=box.querySelector('#cu').value.trim().toLowerCase(),p=box.querySelector('#cp').value;if(!/^[a-z0-9_.-]{4,30}$/.test(u)||p.length<10){alert('اسم مستخدم (4-30 حرفاً لاتينياً/أرقام) وكلمة مرور 10 أحرف على الأقل');return}
const c2=window.supabase.createClient(PORTAL_CFG.SUPABASE_URL,PORTAL_CFG.SUPABASE_KEY,{auth:{persistSession:false,autoRefreshToken:false,storageKey:'pc-tmp'}});
const{data,error}=await c2.auth.signUp({email:u+'@'+PORTAL_CFG.EMAIL_DOMAIN,password:p});if(error||!data.user){alert(error?error.message:'تعذّر الإنشاء');return}
const{error:e2}=await c.from('wajih_profiles').insert({id:data.user.id,username:u,full_name:box.querySelector('#cf').value.trim(),role:box.querySelector('#cr').value,must_change:true});if(e2)alert(e2.message);draw()}}
draw()})})();
